name: superdeck_cli
description: My new Dart CLI package
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  code_builder: ^4.5.0
  dart_style: ^2.3.2
  mason_logger: ^0.2.5
  path: ^1.8.1
  recase: ^4.1.0
  watcher: ^1.0.1
  yaml: ^3.1.2
  palm_api:
    path: ../../../palm_api_dart
  envied: ^0.5.3
  collection: ^1.18.0
  cli_annotations: ^0.1.0-dev.5

dev_dependencies:
  build_runner: ^2.4.6
  build_version: ^2.1.1
  cli_gen: ^0.1.0-dev.5
  dependency_validator: ^3.2.3
  envied_generator: ^0.5.3
  lints: ^2.1.1
  mocktail: ^0.3.0
  test: ^1.24.2

executables:
  superdeck: superdeck
