name: superdeck_cli
description: A cli for SuperDeck
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  mason_logger: ^0.2.12
  path: ^1.8.1
  recase: ^4.1.0
  watcher: ^1.1.0
  yaml: ^3.1.2
  envied: ^0.5.3
  collection: ^1.18.0
  cli_annotations: ^0.1.0-dev.5
  interact: ^2.2.0
  tint: ^2.0.1
  
  dart_console: ^1.2.0

dev_dependencies:
  build_runner: ^2.4.6
  build_version: ^2.1.1
  cli_gen: ^0.1.0-dev.5
  dependency_validator: ^3.2.3
  envied_generator: ^0.5.3
  lints: ^3.0.0
  mocktail: ^1.0.3
  test: ^1.24.2

executables:
  superdeck: superdeck
