name: superdeck_cli
description: A starting point for Dart libraries or applications.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.3.0 <4.0.0"

executables:
  superdeck: main
    

dependencies:
  yaml: ^3.1.2
  args: ^2.5.0
  path: ^1.9.0


dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
