targets:
  $default:
    builders:
      dart_mappable_builder:
        generate_for:
          - lib/**/*.dart
      mix_generator|spec:
        generate_for:
          - lib/**/*.dart
      mix_generator|dto:
        generate_for:
          - lib/**/*.dart
      mix_generator|enum_utility:
        generate_for:
          - lib/**/*.dart
      mix_generator|class_utility:
        generate_for:
          - lib/**/*.dart
      
global_options:
  dart_mappable_builder:
    options:
      caseStyle: snakeCase
      enumCaseStyle: snakeCase
      ignoreNull: true
      generateMethods: [decode, encode, copy, stringify, equals]