name: superdeck
description: Presentation slides for Flutter with Flutter
version: 0.0.4
homepage: https://github.com/leoafarias/superdeck

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  window_manager: ^0.3.9
  collection: ^1.18.0
  path: ^1.9.0
  dart_mappable: ^4.2.2
  yaml: ^3.1.2
  animate_do: ^3.3.4
  recase: ^4.1.0
  syntax_highlight: ^0.4.0
  scrollable_positioned_list: ^0.3.8
  pdf: ^3.10.8
  localstorage: ^5.0.0
  go_router: ^14.1.4
  file_picker: ^8.0.7
  
  path_provider: ^2.1.4
  url_launcher: ^6.2.6
  mix: ^1.4.4
  mix_annotations: ^0.2.1
  flutter_markdown: ^0.7.3
  markdown: ^7.2.2
  flutter_hooks: ^0.20.5
  web: ^0.5.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.10
  dart_mappable_builder: ^4.2.3

  build_verify: ^3.1.0
  mix_generator: ^0.2.2
  custom_lint: ^0.6.4
  mix_lint: ^0.1.1
  
  
flutter:
  assets:
    - grammars/