name: superdeck
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/leoafarias/superdeck

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mix: ^1.0.0-beta.8
  markdown: ^7.1.1
  flutter_markdown: ^0.6.18
  cached_network_image: ^3.3.0
  superdeck_core: ^0.0.1
  window_manager: ^0.3.7
  watcher: ^1.1.0
  shared_preferences: ^2.2.2
  
 
  collection: ^1.17.2
  google_fonts: ^6.1.0
  highlighting: ^0.9.0+11.8.0
  flutter_highlighting: ^0.9.0+11.8.0
  path: ^1.8.3
  syntax_highlight: ^0.2.0
  hooks_riverpod: ^2.4.4
  flutter_hooks: ^0.20.3
  riverpod_annotation: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  riverpod_generator: ^2.3.5
  build_runner: ^2.4.6
  custom_lint: ^0.5.4
  riverpod_lint: ^2.3.2

flutter:
