name: superdeck
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/leoafarias/superdeck

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mix: ^1.0.0-beta.8
  cached_network_image: ^3.3.1
  window_manager: ^0.3.8
  watcher: ^1.1.0
  shared_preferences: ^2.2.2
  collection: ^1.17.2
  google_fonts: ^6.1.0
  path: ^1.9.0
  syntax_highlight: ^0.3.0
  get_it: ^7.6.7
  signals_flutter: ^4.4.0
  dart_mappable: ^4.2.0
  dart_markdown: ^3.1.7
  flutter_prism: ^0.2.2
  markdown_viewer: ^0.6.2
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  custom_lint: ^0.5.11
  build_runner: ^2.4.6
  signals_lint: ^4.2.0
  dart_mappable_builder: ^4.2.0

flutter:
