name: superdeck
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/leoafarias/superdeck

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mix: ^1.0.0-beta.8
  markdown: ^7.2.1
  flutter_markdown: ^0.6.20+1
  cached_network_image: ^3.3.1
  superdeck_core: ^0.0.1
  window_manager: ^0.3.8
  watcher: ^1.1.0
  shared_preferences: ^2.2.2
  collection: ^1.18.0
  google_fonts: ^6.1.0
  highlighting: ^0.9.0+11.8.0
  flutter_highlighting: ^0.9.0+11.8.0
  path: ^1.9.0
  syntax_highlight: ^0.3.0
  get_it: ^7.6.7
  signals_flutter: ^4.4.0
  markdown_widget: ^2.3.2+3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  custom_lint: ^0.5.11
  signals_lint: ^4.2.0

flutter:
