name: superdeck

packages:
  - packages/*

ignore:
  - "packages/**/example"

sdkPath: .fvm/flutter_sdk

command:
  clean:
    hooks:
      post: melos exec --flutter -- "flutter clean"
  bootstrap:
    environment:
        sdk: ">=3.0.0 <4.0.0"
        flutter: ">=3.0.0 <4.0.0"
    runPubGetInParallel: true

scripts:
  analyze:
    exec: dart analyze .
  build_runner:
    exec: dart run build_runner build --delete-conflicting-outputs
    packageFilters:
      dependsOn: [build_runner]
  build_runner_watch:
    exec: dart run build_runner watch --delete-conflicting-outputs
    packageFilters:
      dependsOn: [build_runner] 
  version:
    exec: flutter --version
