name: dash_deck
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/leoafarias/dash_deck

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dash_deck_core:
    path: ../dash_deck_core
  mix:
    path: ../../../mix
  markdown: ^5.0.0
  flutter_markdown: ^0.6.10+1
  cached_network_image: ^3.2.1
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  window_manager: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
