name: dash_deck
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/leoafarias/dash_deck

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mix:
    path: ../../../mix
  markdown: ^7.1.1
  flutter_markdown: ^0.6.17+1
  cached_network_image: ^3.2.3

  dash_deck_core: ^0.0.1

  window_manager: ^0.3.5
  watcher: ^1.1.0
  shared_preferences: ^2.2.0
  flutter_riverpod: ^2.3.7
  riverpod_annotation: ^2.1.2
  collection: ^1.17.2
  google_fonts: ^5.1.0
  highlighting: ^0.9.0+11.8.0
  flutter_highlighting: ^0.9.0+11.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  riverpod_generator: ^2.2.6
  build_runner: ^2.4.6
  custom_lint: ^0.5.2
  riverpod_lint: ^2.0.1

flutter:
