name: dash_deck_cli
description: Presentation Slides for Flutter Developers with Flutter.
version: 0.0.1-dev.0
repository: https://github.com/leoafarias/dash_deck

executables:
  dash_deck: dash_deck

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  args: ^2.3.1
  recase: ^4.0.0
  yaml: ^3.1.1
  collection: ^1.16.0
  path: ^1.8.1
  code_builder: ^4.1.0
  watcher: ^1.0.1
  dart_style: ^2.2.3
  dash_deck_core:
    path: ../dash_deck_core
  mason: ^0.1.0-dev.22

dev_dependencies:
  lints: ^1.0.0
  test: ^1.21.1
