name: dash_deck_cli
description: My new Dart CLI package
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.1
  cli_completion: ^0.3.0
  code_builder: ^4.5.0
  dart_style: ^2.3.2
  dash_deck: ^0.0.1
  mason_logger: ^0.2.5
  path: ^1.8.1
  pub_updater: ^0.3.0
  recase: ^4.1.0
  watcher: ^1.0.1
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.4
  build_verify: ^3.1.0
  build_version: ^2.1.1
  lints: ^2.1.1
  mocktail: ^0.3.0
  test: ^1.24.2

executables:
  dash_deck: dash_deck_cli
