name: superdeck_core
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_mappable: ^4.2.0

dev_dependencies:
  lints: ^3.0.0
  mocktail: ^1.0.3
  test: ^1.25.2
  build_runner: ^2.4.6
  dart_mappable_builder: ^4.0.1
  
  
  
