name: Test Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2

      - run: flutter pub get

      - uses: invertase/github-action-dart-analyzer@v1
        with:
          fatal-infos: false
          
      - run: flutter test